server:
  port: 8081


spring:
  datasource:
    url: jdbc:h2:mem:testdb  # In-memory database (for testing purposes)
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
  h2:
    console:
      enabled: true  # Enables H2 console at /h2-console
logging:
  level:
    org.springframework.jdbc.datasource: DEBUG
    com.zaxxer.hikari: DEBUG